service: my-nodejs-serverless

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  stage: dev

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
